cmake_minimum_required(VERSION 3.25)

#include(AxiomIcon)

set(AXIOM_ROOT "${CMAKE_CURRENT_SOURCE_DIR}")

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/assimp)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/glad)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/glfw)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/glm)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/xsimd)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/wrappers/asio)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/wrappers/lua)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/wrappers/stb)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/external/json)

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/assets)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/ecs)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/input)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/math)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/physics-2d)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/physics-3d)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/platform)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/render)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/scene)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/ui)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/utilities)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/engine/window)