# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(CMAKE_COMMAND) -E cmake_progress_start C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build/CMakeFiles C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom//CMakeFiles/progress.marks
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/rule:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/rule
.PHONY : C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/rule

# Convenience name for target.
lua: C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/rule
.PHONY : lua

# fast build rule for target.
lua/fast:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build
.PHONY : lua/fast

__/__/lua/lapi.obj: __/__/lua/lapi.c.obj
.PHONY : __/__/lua/lapi.obj

# target to build an object file
__/__/lua/lapi.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lapi.c.obj
.PHONY : __/__/lua/lapi.c.obj

__/__/lua/lapi.i: __/__/lua/lapi.c.i
.PHONY : __/__/lua/lapi.i

# target to preprocess a source file
__/__/lua/lapi.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lapi.c.i
.PHONY : __/__/lua/lapi.c.i

__/__/lua/lapi.s: __/__/lua/lapi.c.s
.PHONY : __/__/lua/lapi.s

# target to generate assembly for a file
__/__/lua/lapi.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lapi.c.s
.PHONY : __/__/lua/lapi.c.s

__/__/lua/lauxlib.obj: __/__/lua/lauxlib.c.obj
.PHONY : __/__/lua/lauxlib.obj

# target to build an object file
__/__/lua/lauxlib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lauxlib.c.obj
.PHONY : __/__/lua/lauxlib.c.obj

__/__/lua/lauxlib.i: __/__/lua/lauxlib.c.i
.PHONY : __/__/lua/lauxlib.i

# target to preprocess a source file
__/__/lua/lauxlib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lauxlib.c.i
.PHONY : __/__/lua/lauxlib.c.i

__/__/lua/lauxlib.s: __/__/lua/lauxlib.c.s
.PHONY : __/__/lua/lauxlib.s

# target to generate assembly for a file
__/__/lua/lauxlib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lauxlib.c.s
.PHONY : __/__/lua/lauxlib.c.s

__/__/lua/lbaselib.obj: __/__/lua/lbaselib.c.obj
.PHONY : __/__/lua/lbaselib.obj

# target to build an object file
__/__/lua/lbaselib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lbaselib.c.obj
.PHONY : __/__/lua/lbaselib.c.obj

__/__/lua/lbaselib.i: __/__/lua/lbaselib.c.i
.PHONY : __/__/lua/lbaselib.i

# target to preprocess a source file
__/__/lua/lbaselib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lbaselib.c.i
.PHONY : __/__/lua/lbaselib.c.i

__/__/lua/lbaselib.s: __/__/lua/lbaselib.c.s
.PHONY : __/__/lua/lbaselib.s

# target to generate assembly for a file
__/__/lua/lbaselib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lbaselib.c.s
.PHONY : __/__/lua/lbaselib.c.s

__/__/lua/lcode.obj: __/__/lua/lcode.c.obj
.PHONY : __/__/lua/lcode.obj

# target to build an object file
__/__/lua/lcode.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lcode.c.obj
.PHONY : __/__/lua/lcode.c.obj

__/__/lua/lcode.i: __/__/lua/lcode.c.i
.PHONY : __/__/lua/lcode.i

# target to preprocess a source file
__/__/lua/lcode.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lcode.c.i
.PHONY : __/__/lua/lcode.c.i

__/__/lua/lcode.s: __/__/lua/lcode.c.s
.PHONY : __/__/lua/lcode.s

# target to generate assembly for a file
__/__/lua/lcode.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lcode.c.s
.PHONY : __/__/lua/lcode.c.s

__/__/lua/lcorolib.obj: __/__/lua/lcorolib.c.obj
.PHONY : __/__/lua/lcorolib.obj

# target to build an object file
__/__/lua/lcorolib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lcorolib.c.obj
.PHONY : __/__/lua/lcorolib.c.obj

__/__/lua/lcorolib.i: __/__/lua/lcorolib.c.i
.PHONY : __/__/lua/lcorolib.i

# target to preprocess a source file
__/__/lua/lcorolib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lcorolib.c.i
.PHONY : __/__/lua/lcorolib.c.i

__/__/lua/lcorolib.s: __/__/lua/lcorolib.c.s
.PHONY : __/__/lua/lcorolib.s

# target to generate assembly for a file
__/__/lua/lcorolib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lcorolib.c.s
.PHONY : __/__/lua/lcorolib.c.s

__/__/lua/lctype.obj: __/__/lua/lctype.c.obj
.PHONY : __/__/lua/lctype.obj

# target to build an object file
__/__/lua/lctype.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lctype.c.obj
.PHONY : __/__/lua/lctype.c.obj

__/__/lua/lctype.i: __/__/lua/lctype.c.i
.PHONY : __/__/lua/lctype.i

# target to preprocess a source file
__/__/lua/lctype.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lctype.c.i
.PHONY : __/__/lua/lctype.c.i

__/__/lua/lctype.s: __/__/lua/lctype.c.s
.PHONY : __/__/lua/lctype.s

# target to generate assembly for a file
__/__/lua/lctype.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lctype.c.s
.PHONY : __/__/lua/lctype.c.s

__/__/lua/ldblib.obj: __/__/lua/ldblib.c.obj
.PHONY : __/__/lua/ldblib.obj

# target to build an object file
__/__/lua/ldblib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldblib.c.obj
.PHONY : __/__/lua/ldblib.c.obj

__/__/lua/ldblib.i: __/__/lua/ldblib.c.i
.PHONY : __/__/lua/ldblib.i

# target to preprocess a source file
__/__/lua/ldblib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldblib.c.i
.PHONY : __/__/lua/ldblib.c.i

__/__/lua/ldblib.s: __/__/lua/ldblib.c.s
.PHONY : __/__/lua/ldblib.s

# target to generate assembly for a file
__/__/lua/ldblib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldblib.c.s
.PHONY : __/__/lua/ldblib.c.s

__/__/lua/ldebug.obj: __/__/lua/ldebug.c.obj
.PHONY : __/__/lua/ldebug.obj

# target to build an object file
__/__/lua/ldebug.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldebug.c.obj
.PHONY : __/__/lua/ldebug.c.obj

__/__/lua/ldebug.i: __/__/lua/ldebug.c.i
.PHONY : __/__/lua/ldebug.i

# target to preprocess a source file
__/__/lua/ldebug.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldebug.c.i
.PHONY : __/__/lua/ldebug.c.i

__/__/lua/ldebug.s: __/__/lua/ldebug.c.s
.PHONY : __/__/lua/ldebug.s

# target to generate assembly for a file
__/__/lua/ldebug.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldebug.c.s
.PHONY : __/__/lua/ldebug.c.s

__/__/lua/ldo.obj: __/__/lua/ldo.c.obj
.PHONY : __/__/lua/ldo.obj

# target to build an object file
__/__/lua/ldo.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldo.c.obj
.PHONY : __/__/lua/ldo.c.obj

__/__/lua/ldo.i: __/__/lua/ldo.c.i
.PHONY : __/__/lua/ldo.i

# target to preprocess a source file
__/__/lua/ldo.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldo.c.i
.PHONY : __/__/lua/ldo.c.i

__/__/lua/ldo.s: __/__/lua/ldo.c.s
.PHONY : __/__/lua/ldo.s

# target to generate assembly for a file
__/__/lua/ldo.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldo.c.s
.PHONY : __/__/lua/ldo.c.s

__/__/lua/ldump.obj: __/__/lua/ldump.c.obj
.PHONY : __/__/lua/ldump.obj

# target to build an object file
__/__/lua/ldump.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldump.c.obj
.PHONY : __/__/lua/ldump.c.obj

__/__/lua/ldump.i: __/__/lua/ldump.c.i
.PHONY : __/__/lua/ldump.i

# target to preprocess a source file
__/__/lua/ldump.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldump.c.i
.PHONY : __/__/lua/ldump.c.i

__/__/lua/ldump.s: __/__/lua/ldump.c.s
.PHONY : __/__/lua/ldump.s

# target to generate assembly for a file
__/__/lua/ldump.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ldump.c.s
.PHONY : __/__/lua/ldump.c.s

__/__/lua/lfunc.obj: __/__/lua/lfunc.c.obj
.PHONY : __/__/lua/lfunc.obj

# target to build an object file
__/__/lua/lfunc.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lfunc.c.obj
.PHONY : __/__/lua/lfunc.c.obj

__/__/lua/lfunc.i: __/__/lua/lfunc.c.i
.PHONY : __/__/lua/lfunc.i

# target to preprocess a source file
__/__/lua/lfunc.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lfunc.c.i
.PHONY : __/__/lua/lfunc.c.i

__/__/lua/lfunc.s: __/__/lua/lfunc.c.s
.PHONY : __/__/lua/lfunc.s

# target to generate assembly for a file
__/__/lua/lfunc.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lfunc.c.s
.PHONY : __/__/lua/lfunc.c.s

__/__/lua/lgc.obj: __/__/lua/lgc.c.obj
.PHONY : __/__/lua/lgc.obj

# target to build an object file
__/__/lua/lgc.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lgc.c.obj
.PHONY : __/__/lua/lgc.c.obj

__/__/lua/lgc.i: __/__/lua/lgc.c.i
.PHONY : __/__/lua/lgc.i

# target to preprocess a source file
__/__/lua/lgc.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lgc.c.i
.PHONY : __/__/lua/lgc.c.i

__/__/lua/lgc.s: __/__/lua/lgc.c.s
.PHONY : __/__/lua/lgc.s

# target to generate assembly for a file
__/__/lua/lgc.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lgc.c.s
.PHONY : __/__/lua/lgc.c.s

__/__/lua/linit.obj: __/__/lua/linit.c.obj
.PHONY : __/__/lua/linit.obj

# target to build an object file
__/__/lua/linit.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/linit.c.obj
.PHONY : __/__/lua/linit.c.obj

__/__/lua/linit.i: __/__/lua/linit.c.i
.PHONY : __/__/lua/linit.i

# target to preprocess a source file
__/__/lua/linit.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/linit.c.i
.PHONY : __/__/lua/linit.c.i

__/__/lua/linit.s: __/__/lua/linit.c.s
.PHONY : __/__/lua/linit.s

# target to generate assembly for a file
__/__/lua/linit.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/linit.c.s
.PHONY : __/__/lua/linit.c.s

__/__/lua/liolib.obj: __/__/lua/liolib.c.obj
.PHONY : __/__/lua/liolib.obj

# target to build an object file
__/__/lua/liolib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/liolib.c.obj
.PHONY : __/__/lua/liolib.c.obj

__/__/lua/liolib.i: __/__/lua/liolib.c.i
.PHONY : __/__/lua/liolib.i

# target to preprocess a source file
__/__/lua/liolib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/liolib.c.i
.PHONY : __/__/lua/liolib.c.i

__/__/lua/liolib.s: __/__/lua/liolib.c.s
.PHONY : __/__/lua/liolib.s

# target to generate assembly for a file
__/__/lua/liolib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/liolib.c.s
.PHONY : __/__/lua/liolib.c.s

__/__/lua/llex.obj: __/__/lua/llex.c.obj
.PHONY : __/__/lua/llex.obj

# target to build an object file
__/__/lua/llex.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/llex.c.obj
.PHONY : __/__/lua/llex.c.obj

__/__/lua/llex.i: __/__/lua/llex.c.i
.PHONY : __/__/lua/llex.i

# target to preprocess a source file
__/__/lua/llex.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/llex.c.i
.PHONY : __/__/lua/llex.c.i

__/__/lua/llex.s: __/__/lua/llex.c.s
.PHONY : __/__/lua/llex.s

# target to generate assembly for a file
__/__/lua/llex.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/llex.c.s
.PHONY : __/__/lua/llex.c.s

__/__/lua/lmathlib.obj: __/__/lua/lmathlib.c.obj
.PHONY : __/__/lua/lmathlib.obj

# target to build an object file
__/__/lua/lmathlib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lmathlib.c.obj
.PHONY : __/__/lua/lmathlib.c.obj

__/__/lua/lmathlib.i: __/__/lua/lmathlib.c.i
.PHONY : __/__/lua/lmathlib.i

# target to preprocess a source file
__/__/lua/lmathlib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lmathlib.c.i
.PHONY : __/__/lua/lmathlib.c.i

__/__/lua/lmathlib.s: __/__/lua/lmathlib.c.s
.PHONY : __/__/lua/lmathlib.s

# target to generate assembly for a file
__/__/lua/lmathlib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lmathlib.c.s
.PHONY : __/__/lua/lmathlib.c.s

__/__/lua/lmem.obj: __/__/lua/lmem.c.obj
.PHONY : __/__/lua/lmem.obj

# target to build an object file
__/__/lua/lmem.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lmem.c.obj
.PHONY : __/__/lua/lmem.c.obj

__/__/lua/lmem.i: __/__/lua/lmem.c.i
.PHONY : __/__/lua/lmem.i

# target to preprocess a source file
__/__/lua/lmem.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lmem.c.i
.PHONY : __/__/lua/lmem.c.i

__/__/lua/lmem.s: __/__/lua/lmem.c.s
.PHONY : __/__/lua/lmem.s

# target to generate assembly for a file
__/__/lua/lmem.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lmem.c.s
.PHONY : __/__/lua/lmem.c.s

__/__/lua/loadlib.obj: __/__/lua/loadlib.c.obj
.PHONY : __/__/lua/loadlib.obj

# target to build an object file
__/__/lua/loadlib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/loadlib.c.obj
.PHONY : __/__/lua/loadlib.c.obj

__/__/lua/loadlib.i: __/__/lua/loadlib.c.i
.PHONY : __/__/lua/loadlib.i

# target to preprocess a source file
__/__/lua/loadlib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/loadlib.c.i
.PHONY : __/__/lua/loadlib.c.i

__/__/lua/loadlib.s: __/__/lua/loadlib.c.s
.PHONY : __/__/lua/loadlib.s

# target to generate assembly for a file
__/__/lua/loadlib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/loadlib.c.s
.PHONY : __/__/lua/loadlib.c.s

__/__/lua/lobject.obj: __/__/lua/lobject.c.obj
.PHONY : __/__/lua/lobject.obj

# target to build an object file
__/__/lua/lobject.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lobject.c.obj
.PHONY : __/__/lua/lobject.c.obj

__/__/lua/lobject.i: __/__/lua/lobject.c.i
.PHONY : __/__/lua/lobject.i

# target to preprocess a source file
__/__/lua/lobject.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lobject.c.i
.PHONY : __/__/lua/lobject.c.i

__/__/lua/lobject.s: __/__/lua/lobject.c.s
.PHONY : __/__/lua/lobject.s

# target to generate assembly for a file
__/__/lua/lobject.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lobject.c.s
.PHONY : __/__/lua/lobject.c.s

__/__/lua/lopcodes.obj: __/__/lua/lopcodes.c.obj
.PHONY : __/__/lua/lopcodes.obj

# target to build an object file
__/__/lua/lopcodes.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lopcodes.c.obj
.PHONY : __/__/lua/lopcodes.c.obj

__/__/lua/lopcodes.i: __/__/lua/lopcodes.c.i
.PHONY : __/__/lua/lopcodes.i

# target to preprocess a source file
__/__/lua/lopcodes.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lopcodes.c.i
.PHONY : __/__/lua/lopcodes.c.i

__/__/lua/lopcodes.s: __/__/lua/lopcodes.c.s
.PHONY : __/__/lua/lopcodes.s

# target to generate assembly for a file
__/__/lua/lopcodes.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lopcodes.c.s
.PHONY : __/__/lua/lopcodes.c.s

__/__/lua/loslib.obj: __/__/lua/loslib.c.obj
.PHONY : __/__/lua/loslib.obj

# target to build an object file
__/__/lua/loslib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/loslib.c.obj
.PHONY : __/__/lua/loslib.c.obj

__/__/lua/loslib.i: __/__/lua/loslib.c.i
.PHONY : __/__/lua/loslib.i

# target to preprocess a source file
__/__/lua/loslib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/loslib.c.i
.PHONY : __/__/lua/loslib.c.i

__/__/lua/loslib.s: __/__/lua/loslib.c.s
.PHONY : __/__/lua/loslib.s

# target to generate assembly for a file
__/__/lua/loslib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/loslib.c.s
.PHONY : __/__/lua/loslib.c.s

__/__/lua/lparser.obj: __/__/lua/lparser.c.obj
.PHONY : __/__/lua/lparser.obj

# target to build an object file
__/__/lua/lparser.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lparser.c.obj
.PHONY : __/__/lua/lparser.c.obj

__/__/lua/lparser.i: __/__/lua/lparser.c.i
.PHONY : __/__/lua/lparser.i

# target to preprocess a source file
__/__/lua/lparser.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lparser.c.i
.PHONY : __/__/lua/lparser.c.i

__/__/lua/lparser.s: __/__/lua/lparser.c.s
.PHONY : __/__/lua/lparser.s

# target to generate assembly for a file
__/__/lua/lparser.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lparser.c.s
.PHONY : __/__/lua/lparser.c.s

__/__/lua/lstate.obj: __/__/lua/lstate.c.obj
.PHONY : __/__/lua/lstate.obj

# target to build an object file
__/__/lua/lstate.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstate.c.obj
.PHONY : __/__/lua/lstate.c.obj

__/__/lua/lstate.i: __/__/lua/lstate.c.i
.PHONY : __/__/lua/lstate.i

# target to preprocess a source file
__/__/lua/lstate.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstate.c.i
.PHONY : __/__/lua/lstate.c.i

__/__/lua/lstate.s: __/__/lua/lstate.c.s
.PHONY : __/__/lua/lstate.s

# target to generate assembly for a file
__/__/lua/lstate.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstate.c.s
.PHONY : __/__/lua/lstate.c.s

__/__/lua/lstring.obj: __/__/lua/lstring.c.obj
.PHONY : __/__/lua/lstring.obj

# target to build an object file
__/__/lua/lstring.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstring.c.obj
.PHONY : __/__/lua/lstring.c.obj

__/__/lua/lstring.i: __/__/lua/lstring.c.i
.PHONY : __/__/lua/lstring.i

# target to preprocess a source file
__/__/lua/lstring.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstring.c.i
.PHONY : __/__/lua/lstring.c.i

__/__/lua/lstring.s: __/__/lua/lstring.c.s
.PHONY : __/__/lua/lstring.s

# target to generate assembly for a file
__/__/lua/lstring.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstring.c.s
.PHONY : __/__/lua/lstring.c.s

__/__/lua/lstrlib.obj: __/__/lua/lstrlib.c.obj
.PHONY : __/__/lua/lstrlib.obj

# target to build an object file
__/__/lua/lstrlib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstrlib.c.obj
.PHONY : __/__/lua/lstrlib.c.obj

__/__/lua/lstrlib.i: __/__/lua/lstrlib.c.i
.PHONY : __/__/lua/lstrlib.i

# target to preprocess a source file
__/__/lua/lstrlib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstrlib.c.i
.PHONY : __/__/lua/lstrlib.c.i

__/__/lua/lstrlib.s: __/__/lua/lstrlib.c.s
.PHONY : __/__/lua/lstrlib.s

# target to generate assembly for a file
__/__/lua/lstrlib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lstrlib.c.s
.PHONY : __/__/lua/lstrlib.c.s

__/__/lua/ltable.obj: __/__/lua/ltable.c.obj
.PHONY : __/__/lua/ltable.obj

# target to build an object file
__/__/lua/ltable.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltable.c.obj
.PHONY : __/__/lua/ltable.c.obj

__/__/lua/ltable.i: __/__/lua/ltable.c.i
.PHONY : __/__/lua/ltable.i

# target to preprocess a source file
__/__/lua/ltable.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltable.c.i
.PHONY : __/__/lua/ltable.c.i

__/__/lua/ltable.s: __/__/lua/ltable.c.s
.PHONY : __/__/lua/ltable.s

# target to generate assembly for a file
__/__/lua/ltable.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltable.c.s
.PHONY : __/__/lua/ltable.c.s

__/__/lua/ltablib.obj: __/__/lua/ltablib.c.obj
.PHONY : __/__/lua/ltablib.obj

# target to build an object file
__/__/lua/ltablib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltablib.c.obj
.PHONY : __/__/lua/ltablib.c.obj

__/__/lua/ltablib.i: __/__/lua/ltablib.c.i
.PHONY : __/__/lua/ltablib.i

# target to preprocess a source file
__/__/lua/ltablib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltablib.c.i
.PHONY : __/__/lua/ltablib.c.i

__/__/lua/ltablib.s: __/__/lua/ltablib.c.s
.PHONY : __/__/lua/ltablib.s

# target to generate assembly for a file
__/__/lua/ltablib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltablib.c.s
.PHONY : __/__/lua/ltablib.c.s

__/__/lua/ltests.obj: __/__/lua/ltests.c.obj
.PHONY : __/__/lua/ltests.obj

# target to build an object file
__/__/lua/ltests.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltests.c.obj
.PHONY : __/__/lua/ltests.c.obj

__/__/lua/ltests.i: __/__/lua/ltests.c.i
.PHONY : __/__/lua/ltests.i

# target to preprocess a source file
__/__/lua/ltests.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltests.c.i
.PHONY : __/__/lua/ltests.c.i

__/__/lua/ltests.s: __/__/lua/ltests.c.s
.PHONY : __/__/lua/ltests.s

# target to generate assembly for a file
__/__/lua/ltests.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltests.c.s
.PHONY : __/__/lua/ltests.c.s

__/__/lua/ltm.obj: __/__/lua/ltm.c.obj
.PHONY : __/__/lua/ltm.obj

# target to build an object file
__/__/lua/ltm.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltm.c.obj
.PHONY : __/__/lua/ltm.c.obj

__/__/lua/ltm.i: __/__/lua/ltm.c.i
.PHONY : __/__/lua/ltm.i

# target to preprocess a source file
__/__/lua/ltm.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltm.c.i
.PHONY : __/__/lua/ltm.c.i

__/__/lua/ltm.s: __/__/lua/ltm.c.s
.PHONY : __/__/lua/ltm.s

# target to generate assembly for a file
__/__/lua/ltm.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/ltm.c.s
.PHONY : __/__/lua/ltm.c.s

__/__/lua/lua.obj: __/__/lua/lua.c.obj
.PHONY : __/__/lua/lua.obj

# target to build an object file
__/__/lua/lua.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lua.c.obj
.PHONY : __/__/lua/lua.c.obj

__/__/lua/lua.i: __/__/lua/lua.c.i
.PHONY : __/__/lua/lua.i

# target to preprocess a source file
__/__/lua/lua.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lua.c.i
.PHONY : __/__/lua/lua.c.i

__/__/lua/lua.s: __/__/lua/lua.c.s
.PHONY : __/__/lua/lua.s

# target to generate assembly for a file
__/__/lua/lua.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lua.c.s
.PHONY : __/__/lua/lua.c.s

__/__/lua/lundump.obj: __/__/lua/lundump.c.obj
.PHONY : __/__/lua/lundump.obj

# target to build an object file
__/__/lua/lundump.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lundump.c.obj
.PHONY : __/__/lua/lundump.c.obj

__/__/lua/lundump.i: __/__/lua/lundump.c.i
.PHONY : __/__/lua/lundump.i

# target to preprocess a source file
__/__/lua/lundump.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lundump.c.i
.PHONY : __/__/lua/lundump.c.i

__/__/lua/lundump.s: __/__/lua/lundump.c.s
.PHONY : __/__/lua/lundump.s

# target to generate assembly for a file
__/__/lua/lundump.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lundump.c.s
.PHONY : __/__/lua/lundump.c.s

__/__/lua/lutf8lib.obj: __/__/lua/lutf8lib.c.obj
.PHONY : __/__/lua/lutf8lib.obj

# target to build an object file
__/__/lua/lutf8lib.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lutf8lib.c.obj
.PHONY : __/__/lua/lutf8lib.c.obj

__/__/lua/lutf8lib.i: __/__/lua/lutf8lib.c.i
.PHONY : __/__/lua/lutf8lib.i

# target to preprocess a source file
__/__/lua/lutf8lib.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lutf8lib.c.i
.PHONY : __/__/lua/lutf8lib.c.i

__/__/lua/lutf8lib.s: __/__/lua/lutf8lib.c.s
.PHONY : __/__/lua/lutf8lib.s

# target to generate assembly for a file
__/__/lua/lutf8lib.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lutf8lib.c.s
.PHONY : __/__/lua/lutf8lib.c.s

__/__/lua/lvm.obj: __/__/lua/lvm.c.obj
.PHONY : __/__/lua/lvm.obj

# target to build an object file
__/__/lua/lvm.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lvm.c.obj
.PHONY : __/__/lua/lvm.c.obj

__/__/lua/lvm.i: __/__/lua/lvm.c.i
.PHONY : __/__/lua/lvm.i

# target to preprocess a source file
__/__/lua/lvm.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lvm.c.i
.PHONY : __/__/lua/lvm.c.i

__/__/lua/lvm.s: __/__/lua/lvm.c.s
.PHONY : __/__/lua/lvm.s

# target to generate assembly for a file
__/__/lua/lvm.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lvm.c.s
.PHONY : __/__/lua/lvm.c.s

__/__/lua/lzio.obj: __/__/lua/lzio.c.obj
.PHONY : __/__/lua/lzio.obj

# target to build an object file
__/__/lua/lzio.c.obj:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lzio.c.obj
.PHONY : __/__/lua/lzio.c.obj

__/__/lua/lzio.i: __/__/lua/lzio.c.i
.PHONY : __/__/lua/lzio.i

# target to preprocess a source file
__/__/lua/lzio.c.i:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lzio.c.i
.PHONY : __/__/lua/lzio.c.i

__/__/lua/lzio.s: __/__/lua/lzio.c.s
.PHONY : __/__/lua/lzio.s

# target to generate assembly for a file
__/__/lua/lzio.c.s:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(MAKE) $(MAKESILENT) -f C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/build.make C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/external/axiom/CMakeFiles/lua.dir/__/__/lua/lzio.c.s
.PHONY : __/__/lua/lzio.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lua"
	@echo "... __/__/lua/lapi.obj"
	@echo "... __/__/lua/lapi.i"
	@echo "... __/__/lua/lapi.s"
	@echo "... __/__/lua/lauxlib.obj"
	@echo "... __/__/lua/lauxlib.i"
	@echo "... __/__/lua/lauxlib.s"
	@echo "... __/__/lua/lbaselib.obj"
	@echo "... __/__/lua/lbaselib.i"
	@echo "... __/__/lua/lbaselib.s"
	@echo "... __/__/lua/lcode.obj"
	@echo "... __/__/lua/lcode.i"
	@echo "... __/__/lua/lcode.s"
	@echo "... __/__/lua/lcorolib.obj"
	@echo "... __/__/lua/lcorolib.i"
	@echo "... __/__/lua/lcorolib.s"
	@echo "... __/__/lua/lctype.obj"
	@echo "... __/__/lua/lctype.i"
	@echo "... __/__/lua/lctype.s"
	@echo "... __/__/lua/ldblib.obj"
	@echo "... __/__/lua/ldblib.i"
	@echo "... __/__/lua/ldblib.s"
	@echo "... __/__/lua/ldebug.obj"
	@echo "... __/__/lua/ldebug.i"
	@echo "... __/__/lua/ldebug.s"
	@echo "... __/__/lua/ldo.obj"
	@echo "... __/__/lua/ldo.i"
	@echo "... __/__/lua/ldo.s"
	@echo "... __/__/lua/ldump.obj"
	@echo "... __/__/lua/ldump.i"
	@echo "... __/__/lua/ldump.s"
	@echo "... __/__/lua/lfunc.obj"
	@echo "... __/__/lua/lfunc.i"
	@echo "... __/__/lua/lfunc.s"
	@echo "... __/__/lua/lgc.obj"
	@echo "... __/__/lua/lgc.i"
	@echo "... __/__/lua/lgc.s"
	@echo "... __/__/lua/linit.obj"
	@echo "... __/__/lua/linit.i"
	@echo "... __/__/lua/linit.s"
	@echo "... __/__/lua/liolib.obj"
	@echo "... __/__/lua/liolib.i"
	@echo "... __/__/lua/liolib.s"
	@echo "... __/__/lua/llex.obj"
	@echo "... __/__/lua/llex.i"
	@echo "... __/__/lua/llex.s"
	@echo "... __/__/lua/lmathlib.obj"
	@echo "... __/__/lua/lmathlib.i"
	@echo "... __/__/lua/lmathlib.s"
	@echo "... __/__/lua/lmem.obj"
	@echo "... __/__/lua/lmem.i"
	@echo "... __/__/lua/lmem.s"
	@echo "... __/__/lua/loadlib.obj"
	@echo "... __/__/lua/loadlib.i"
	@echo "... __/__/lua/loadlib.s"
	@echo "... __/__/lua/lobject.obj"
	@echo "... __/__/lua/lobject.i"
	@echo "... __/__/lua/lobject.s"
	@echo "... __/__/lua/lopcodes.obj"
	@echo "... __/__/lua/lopcodes.i"
	@echo "... __/__/lua/lopcodes.s"
	@echo "... __/__/lua/loslib.obj"
	@echo "... __/__/lua/loslib.i"
	@echo "... __/__/lua/loslib.s"
	@echo "... __/__/lua/lparser.obj"
	@echo "... __/__/lua/lparser.i"
	@echo "... __/__/lua/lparser.s"
	@echo "... __/__/lua/lstate.obj"
	@echo "... __/__/lua/lstate.i"
	@echo "... __/__/lua/lstate.s"
	@echo "... __/__/lua/lstring.obj"
	@echo "... __/__/lua/lstring.i"
	@echo "... __/__/lua/lstring.s"
	@echo "... __/__/lua/lstrlib.obj"
	@echo "... __/__/lua/lstrlib.i"
	@echo "... __/__/lua/lstrlib.s"
	@echo "... __/__/lua/ltable.obj"
	@echo "... __/__/lua/ltable.i"
	@echo "... __/__/lua/ltable.s"
	@echo "... __/__/lua/ltablib.obj"
	@echo "... __/__/lua/ltablib.i"
	@echo "... __/__/lua/ltablib.s"
	@echo "... __/__/lua/ltests.obj"
	@echo "... __/__/lua/ltests.i"
	@echo "... __/__/lua/ltests.s"
	@echo "... __/__/lua/ltm.obj"
	@echo "... __/__/lua/ltm.i"
	@echo "... __/__/lua/ltm.s"
	@echo "... __/__/lua/lua.obj"
	@echo "... __/__/lua/lua.i"
	@echo "... __/__/lua/lua.s"
	@echo "... __/__/lua/lundump.obj"
	@echo "... __/__/lua/lundump.i"
	@echo "... __/__/lua/lundump.s"
	@echo "... __/__/lua/lutf8lib.obj"
	@echo "... __/__/lua/lutf8lib.i"
	@echo "... __/__/lua/lutf8lib.s"
	@echo "... __/__/lua/lvm.obj"
	@echo "... __/__/lua/lvm.i"
	@echo "... __/__/lua/lvm.s"
	@echo "... __/__/lua/lzio.obj"
	@echo "... __/__/lua/lzio.i"
	@echo "... __/__/lua/lzio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd C:/Users/plane/OneDrive/Documents/GitHub/Physics-Test/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

