#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba16, binding = 0) uniform image3D output_img;

layout(location = 0) uniform uint seed;
layout(location = 1) uniform float period;
layout(location = 2) uniform uint octaves;
layout(location = 3) uniform vec3 origin;
layout(location = 4) uniform vec3 range;

float maximum_3d = 1.5 / sqrt(3);

uint hash(uint x) {
    x ^= x >> 16;
    x *= 0x7feb352dU;
    x ^= x >> 15;
    x *= 0x846ca68bU;
    x ^= x >> 16;
    return x;
}

uint hash(uvec2 v) { 
    return hash(v.x ^ hash(v.y)); 
}

uint hash(uvec3 v) { 
    return hash(v.x ^ hash(v.y)) ^ hash(v.z); 
}

uint hash(uvec4 v) {
    return hash(v.x ^ hash(v.y)) ^ hash(v.z) ^ hash(v.w); 
}

float to_float(uint m) {
    const uint ieeeMantissa = 0x007FFFFFu; // binary32 mantissa bitmask
    const uint ieeeOne = 0x3F800000u; // 1.0 in IEEE binary32

    m &= ieeeMantissa;                     // Keep only mantissa bits (fractional part)
    m |= ieeeOne;                          // Add fractional part to 1.0

    float  f = uintBitsToFloat(m);       // Range [1:2]
    return f * 2.0 - 3.0;                // Range [-1:1]
}

vec3 random_vector(ivec3 seed_a, uint seed_b) {
    uvec3 new_seed_a = uvec3(seed_a);
    
    uint hash_b = seed_b;

    vec3 unit_vector;
    float u_length = 10;
    while(u_length > 1.0 || u_length == 0.0) {
        hash_b = hash(hash_b);
        float x = to_float(hash(new_seed_a) ^ hash_b);
        hash_b = hash(hash_b);
        float y = to_float(hash(new_seed_a) ^ hash_b);
        hash_b = hash(hash_b);
        float z = to_float(hash(new_seed_a) ^ hash_b);

        unit_vector = vec3(x, y, z);
        u_length = length(unit_vector);
    }

    return normalize(unit_vector);
}

float perlin_noise(vec3 location, float period, uint octaves, uint seed) {
    float sum = 0.0;
    float maximum = 0.0;

    vec3 global_loc = location / period;

    for(int i = 0; i < octaves; ++i) {
        ivec3 corner_id = ivec3(floor(global_loc));
        vec3 fractional = fract(global_loc);
        ivec3 vector_origins[8] = {
            corner_id,
            corner_id + ivec3(1, 0, 0),
            corner_id + ivec3(0, 1, 0),
            corner_id + ivec3(1, 1, 0),
            corner_id + ivec3(0, 0, 1),
            corner_id + ivec3(1, 0, 1),
            corner_id + ivec3(0, 1, 1),
            corner_id + ivec3(1, 1, 1)
        };
        
        vec3 vectors[8] = {
            random_vector(vector_origins[0], seed),
            random_vector(vector_origins[1], seed),
            random_vector(vector_origins[2], seed),
            random_vector(vector_origins[3], seed),
            random_vector(vector_origins[4], seed),
            random_vector(vector_origins[5], seed),
            random_vector(vector_origins[6], seed),
            random_vector(vector_origins[7], seed)
        };

        fractional = smoothstep(0.0, 1.0, fractional);

        float v = mix(
            mix(
            mix(dot(vectors[0], global_loc - vector_origins[0]), dot(vectors[1], global_loc - vector_origins[1]), fractional.x), 
            mix(dot(vectors[2], global_loc - vector_origins[2]), dot(vectors[3], global_loc - vector_origins[3]), fractional.x), fractional.y),
            mix(
            mix(dot(vectors[4], global_loc - vector_origins[4]), dot(vectors[5], global_loc - vector_origins[5]), fractional.x), 
            mix(dot(vectors[6], global_loc - vector_origins[6]), dot(vectors[7], global_loc - vector_origins[7]), fractional.x), fractional.y), fractional.z);
        
        float power = pow(0.5, i);
        sum += v * power;
        maximum += maximum_3d * power;

        global_loc *= 2;
    }

    sum /= maximum;
    sum = sum * 0.5 + 0.5;

    return sum;
}

float ridged_perlin_noise(vec3 location, float period, uint octaves, uint seed) {
    float sum = 0.0;
    float maximum = 0.0;

    vec3 global_loc = location / period;

    for(int i = 0; i < octaves; ++i) {
        ivec3 corner_id = ivec3(floor(global_loc));
        vec3 fractional = fract(global_loc);
        ivec3 vector_origins[8] = {
            corner_id,
            corner_id + ivec3(1, 0, 0),
            corner_id + ivec3(0, 1, 0),
            corner_id + ivec3(1, 1, 0),
            corner_id + ivec3(0, 0, 1),
            corner_id + ivec3(1, 0, 1),
            corner_id + ivec3(0, 1, 1),
            corner_id + ivec3(1, 1, 1)
        };
        
        vec3 vectors[8] = {
            random_vector(vector_origins[0], seed),
            random_vector(vector_origins[1], seed),
            random_vector(vector_origins[2], seed),
            random_vector(vector_origins[3], seed),
            random_vector(vector_origins[4], seed),
            random_vector(vector_origins[5], seed),
            random_vector(vector_origins[6], seed),
            random_vector(vector_origins[7], seed)
        };

        fractional = smoothstep(0.0, 1.0, fractional);

        float v = mix(
            mix(
            mix(dot(vectors[0], global_loc - vector_origins[0]), dot(vectors[1], global_loc - vector_origins[1]), fractional.x), 
            mix(dot(vectors[2], global_loc - vector_origins[2]), dot(vectors[3], global_loc - vector_origins[3]), fractional.x), fractional.y),
            mix(
            mix(dot(vectors[4], global_loc - vector_origins[4]), dot(vectors[5], global_loc - vector_origins[5]), fractional.x), 
            mix(dot(vectors[6], global_loc - vector_origins[6]), dot(vectors[7], global_loc - vector_origins[7]), fractional.x), fractional.y), fractional.z);
        
        v = maximum_3d - abs(v);
        float power = pow(0.5, i);
        sum += v * power;
        maximum += maximum_3d * power;

        global_loc *= 2;
    }

    sum /= maximum;

    return sum;
}

void main() {
    ivec3 texel_coord = ivec3(gl_GlobalInvocationID.xyz);
    
    vec3 screen_pos = vec3(texel_coord) / gl_NumWorkGroups.xyz;
    vec3 global_loc = origin + range * screen_pos;
    
    float e = ridged_perlin_noise(global_loc, 1024, 4, 500);

    float p = perlin_noise(global_loc, 1024, 2, seed);

    float t = 0.0;

    float v = perlin_noise(global_loc, 128, 4, 500);

    vec4 value = vec4(e, p, t, v);
	
    imageStore(output_img, texel_coord, value);
}