#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba8, binding = 0) uniform image2D output_img;

layout(location = 0) uniform mat4 inv_proj;
layout(location = 1) uniform mat4 inv_view;
layout(location = 2) uniform vec3 player_pos;

float infinity = 1.0 / 0.0;

float sphere_intersection(vec3 pos, vec3 ray_dir, vec3 center, float radius) {
    float center_v = dot(center - pos, ray_dir);
    float dist = length(pos + ray_dir * center_v - center);
    
    if(dist > radius) return -1;
    float a = sqrt(radius * radius - dist * dist);
    if(center_v + a < 0) return -1;

    return max(center_v - a, 0);
}

vec3 sphere_normal(vec3 pos, vec3 center) {
    return normalize(pos - center);
}

vec3 light_direction = normalize(vec3(0.8, 0.9, 1.0));

struct Material {
    vec3 color;
    float reflectivity;
};

struct Sphere {
    vec3 position;
    float radius;

    Material material;
};

struct Plane {
    vec3 position;
    vec3 normal;

    Material material;
};

const int num_spheres = 3;
float intensity_falloff = 0.5;

Sphere spheres[num_spheres] = {
    Sphere(vec3(8, 0, 0), 5, Material(vec3(1.0, 1.0, 0.3), 0.9)),
    Sphere(vec3(13, 7, 1), 3, Material(vec3(1.0, 1.0, 1.0), 0.2)),
    Sphere(vec3(0, 0, -206), 200, Material(vec3(1.0, 1.0, 1.0), 0.2))
};

/*Plane planes[num_planes] = {
    Plane(vec3(0, 0, -6), vec3(0, 0, 1), );
}*/

float get_intensity(vec3 incidence, vec3 normal) {
    float n = 1.3;

    float cosine = dot(incidence, normal);
    float R = pow((n - 1.0) / (n + 1.0), 2);

    float r = R + (1 - R) * pow((1 - cosine), 5);

    return r;

    /*float cosine = dot(incidence, normal);
    float sine = length(cross(incidence, normal));

    float s1 = sqrt(1.0 - pow(n1 / n2 * sine, 2));

    float s = (n1 * cosine - n2 * s1) / (n1 * cosine + n2 * s1);
    float p = (n1 * s1 - n2 * cosine) / (n1 * s1 + n2 * cosine);
    s = pow(s, 2);
    p = pow(p, 2);

    return (s + p) * 0.5;*/
}

struct Light {
    vec3 position;
    vec3 color;
};

const int num_lights = 1;

Light lights[num_lights] = {
    Light(vec3(190, 55, 100), vec3(1.0, 1.0, 1.0))
    //Light(vec3(-90, -55, 250), vec3(1.0, 1.0, 0.0))
};

const int num_bounces = 2;

void main() {
    float transmittance = 1.0;
    bool is_reflection = false;

    vec2 image_size = imageSize(output_img);

    vec2 screen_pos = vec2(gl_GlobalInvocationID.xy) / image_size * 2 - 1;

    vec4 ray_p = inv_proj * vec4(screen_pos, 0.25, 1.0);
    ray_p /= ray_p.w;

    ray_p = inv_view * ray_p;

    vec3 ray_origin = vec3(inv_view * vec4(0.0, 0.0, 0.0, 1.0));

    vec3 ray_direction = normalize(ray_p.xyz - ray_origin);

    float reflection_value = 1;
    int bounces = 0;
    
    ray_origin += player_pos;

    vec3 color = vec3(0.0, 0.0, 0.0);
    vec3 ray_position = ray_origin;
    for(int i = 0; i < 200; ++i) {
        int closest_sphere = -1;
        float dist = infinity;
        for(int j = 0; j < num_spheres; ++j) {
            Sphere s = spheres[j];
            float d = sphere_intersection(ray_position, ray_direction, s.position, s.radius);
            if(d != -1) {
                if(d < dist) {
                    dist = d;
                    closest_sphere = j; 
                }
            }
        }

        if(dist == infinity) break;

        ray_position += ray_direction * dist;

        Sphere s = spheres[closest_sphere];

        vec3 normal = sphere_normal(ray_position, s.position);

        vec3 incoming_light = vec3(0.0, 0.0, 0.0);


        for(int j = 0; j < num_lights; ++j) {
            //'bool lit = true;
            bool lit = false;
            vec3 light_ray_direction = normalize(ray_position - lights[j].position);
            vec3 light_ray_position = lights[j].position;

            float lambert = clamp(0.0, 1.0, dot(normal, -light_ray_direction));

            float dist = infinity;
            int closest_sphere = -1;
        
            for(int l = 0; l < num_spheres; ++l) {
                Sphere s = spheres[l];
                float d = sphere_intersection(light_ray_position, light_ray_direction, s.position, s.radius);
                if(d != -1) {
                    if(d < dist) {
                        dist = d;
                        closest_sphere = l; 
                    }
                }
            }

            float light_dist = length(ray_position - lights[j].position);

            if(light_dist < dist + 0.002) {
                lit = true;
            }
            
            light_ray_position += light_ray_direction * dist;

            if(lit) {
                incoming_light += lights[j].color * s.material.color * lambert * reflection_value;
            }
        }

        color += incoming_light;

        reflection_value *= s.material.reflectivity;

        /*vec3 light_dir = ray_position - light_position;

        float light_dist

        float sun_dir = */
        
        ray_position += normal * 0.002;

        ray_direction = reflect(ray_direction, normal);
        ++bounces;

        if(bounces >= num_bounces) break;
    }

    color += vec3(0.2, 0.6, 1.0) * reflection_value;

    imageStore(output_img, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0));
}